name: Release

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"
      - "test/**"

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Publish GH release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          generate_release_notes: true

      - name: Build using Poetry and publish to PyPI
        uses: JRubics/poetry-publish@7100bd02517e9f82452e6247849042f6c74dde04 # v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_KEY }}
